2024-04-17 00:16:21,481 ERROR Any error
Traceback (most recent call last):
  File "/tmp/ipykernel_9862/3408752807.py", line 18, in outside_exception
    "hello" + 7
TypeError: can only concatenate str (not "int") to str
